### ISSUE TITLE
注册时用户名已存在不提示

### ISSUE THREAD

**Issue by xiaoheiit6** [ntoj/ntoj#25]
![image](https://github.com/ntoj/ntoj/assets/107839576/6b083bc8-348e-4713-805f-d3177343ef1e)

**Comment by gtn1024** [comment]
fixed in https://github.com/ntoj/ntoj/commit/cf2316048c062b578167dd24bf76bdd8c40f552a

**Comment by gtn1024** [comment]
fixed in https://github.com/ntoj/ntoj/commit/cf2316048c062b578167dd24bf76bdd8c40f552a
